---
title: "airline"
author: "minsun Kim"
date: '2022-09-26'
output: html_document
---


Work in progress.

```{r}
library(nycflights13)
library(tidyverse)
library(here)
library(janitor)
```


```{r}
thisfile=here("DL_SelectFields2022.zip")

df2022=read_csv(thisfile) %>% clean_names()
```

```{r}
thisfile=here("airline_data_2021 (1).zip")

df2021=read_csv(thisfile) %>% clean_names()
```

```{r}
thisfile=here("DL_SelectFields_2020.zip")

df2020=read_csv(thisfile) %>% clean_names()
```

```{r}
thisfile=here("airline_data_2018.zip")

df2018=read_csv(thisfile) %>% clean_names()
```

```{r}
thisfile=here("DL_SelectFields_2017.zip")

df2017=read_csv(thisfile) %>% clean_names()
```

```{r}
df1 = df2022 %>%
  filter(passengers>0, carrier_name=="Republic Airline")

df1 %>% ggplot(aes(x=month, y=passengers)) + geom_bar(stat="identity")
```

```{r}
df2 = df2021 %>%
  filter(passengers>0, carrier_name=="Republic Airline")

df2 %>% ggplot(aes(x=month, y=passengers)) + geom_bar(stat="identity")
```

```{r}
df3 = df2020 %>%
  filter(passengers>0, carrier_name=="Republic Airline")

df3 %>% ggplot(aes(x=month, y=passengers)) + geom_bar(stat="identity")
```

```{r}
df4 = df2018 %>%
  filter(passengers>0, carrier_name=="Republic Airline")

df4 %>% ggplot(aes(x=month, y=passengers)) + geom_bar(stat="identity")
```

```{r}
df5 = df2017 %>%
  filter(passengers>0, carrier_name=="Republic Airline")

df5 %>% ggplot(aes(x=month, y=passengers)) + geom_bar(stat="identity")
```

